### ISSUE TITLE
Datasets for Urdu

### ISSUE THREAD

**Issue by abdulwadood10** [Bushramjad/Speech-Recognition-in-Urdu#1]
Hey @Bushramjad can you provide `NLP_A7_dataset1500.csv` on your repo so I can work on your file?

**Comment by Bushramjad** [comment]
@abdulwadood10 I have added the transcripted file.

**Comment by abdulwadood10** [comment]
Thanks for that. Although I ran through your code with different csv file and there is one more issue..

`model = Wav2Vec2ForCTC.from_pretrained("/content/gdrive/MyDrive/wav2vec2-urdu/checkpoint-800").to("cuda")
processor = Wav2Vec2Processor.from_pretrained("/content/gdrive/MyDrive/wav2vec2-urdu/checkpoint-800")`

After running through this code I face this error 
![image](https://user-images.githubusercontent.com/45212721/151462008-b11a17e2-8b0e-4d27-8df4-50854798ef4b.png)

can you point me where this `"/content/gdrive/MyDrive/wav2vec2-urdu/checkpoint-800"` file or link coming from? I am almost finished running with your code.

**Comment by Bushramjad** [comment]
This path is for model saving in the drive after certain checkpoints. You can add your own drive path or you can remove it completely if you do not want to save your model after a certain period during training.

**Comment by abdulwadood10** [comment]
Alright, so this is saving the model on your own huggingface drive right? 

What if I want to save it on my own local machine so I can run it offline. 

I will be giving my folder path to the to 'pre_trained' parameter?

**Comment by Bushramjad** [comment]
I believe that you can not save it on your local machine. what you can do is, save it in the drive and download it later to use it on the local machine.
