### ISSUE TITLE
Urdu Dataset

### ISSUE THREAD

**Issue by amaddurrani** [Bushramjad/Speech-Recognition-in-Urdu#2]
AOA,
I need the dataset it will be appreciated if you please share google drive link or share data. if it is not possible please share the directory hierarchy for the test and training Data
Thank you

**Comment by amaddurrani** [comment]
amadatiq786@gmail.com

**Comment by Bushramjad** [comment]
Dear Amad, I have provided the transcripted file, I can not share with you the .wav files folder. The hierarchy is simple just a folder having all the .wav files and a CSV file having all the transcriptions.

**Comment by amaddurrani** [comment]
Thank you so much I have done that now the problem is how you saved the checkpoint did you took from Harveenchadha/vakyansh-wav2vec2-urdu-urm-60 there or somewhere else please guide me

**Comment by Bushramjad** [comment]
No, I have used the below-mentioned notebook as a base that is trained for the Turkish Language. You might get some help from here, 
https://colab.research.google.com/github/patrickvonplaten/notebooks/blob/master/Fine_Tune_XLSR_Wav2Vec2_on_Turkish_ASR_with_%F0%9F%A4%97_Transformers.ipynb 

or the discussion from the following site.
https://discuss.huggingface.co/t/turkish-asr-fine-tuning-wav2vec2/4556
