### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by 91Abdullah** [Bushramjad/Speech-Recognition-in-Urdu#4]
Hi,

This looks promising! But do you have a pre-trained model so someone like me can test or deploy it?

**Comment by Bushramjad** [comment]
@91Abdullah I have used facebook's Wav2Vec2ForCTC model. You can use it via the transformers library.

**Comment by 91Abdullah** [comment]
@Bushramjad thanks for responding. I'll explain what I asked. You had data and you trained your model but I don't have data so I can't train but if you can send me your pretrained model I can also use it without actually training. It is like transfer learning!

**Comment by Bushramjad** [comment]
@91Abdullah I am afraid I won't have any now.

**Comment by 91Abdullah** [comment]
What about this checkpoint /content/gdrive/MyDrive/wav2vec2-urdu/checkpoint-800 do you have it?

**Comment by Bushramjad** [comment]
I do not have it now.
